# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-02 16:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartcar', '0002_userprofiledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('chasis_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacture_date', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Not Required', 'Not Required'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Not Required', max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
